# Generated by Django 3.0.7 on 2020-06-16 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.Comment'),
        ),
    ]
